"use client";
import { FormEvent, useState } from "react";
import { CheckCircle2, Mail, MapPin, Phone, Send } from "lucide-react";

const initial = { name: "", email: "", subject: "", message: "" };
const details = [[Mail, "Email", "contact@proguardweb.com"], [Phone, "Phone", "+212 6 XX XX XX XX"], [MapPin, "Location", "Casablanca, Morocco"]] as const;

export default function Contact() {
  const [form, setForm] = useState(initial);
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); try { // TODO: Send the validated form payload to the production contact endpoint.
    await Promise.resolve(form); setForm(initial); setStatus("success"); } catch { setStatus("error"); } }
  return <section id="contact" className="section bg-[#081321]"><div className="container grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><span className="eyebrow">Let&apos;s talk</span><h2 className="section-title">Build a stronger digital presence.</h2><p className="section-copy">Tell us what you&apos;re working on. We&apos;ll come back with a thoughtful next step within one business day.</p><div className="mt-8 grid gap-3">{details.map(([Icon, label, value]) => <div key={label} className="flex items-center gap-3 text-sm"><span className="grid size-9 place-items-center rounded-lg bg-cyan-300/10 text-cyan-200"><Icon className="size-4"/></span><span><b className="block font-medium text-slate-200">{label}</b><span className="text-slate-500">{value}</span></span></div>)}</div></div><form onSubmit={submit} className="surface premium-card rounded-3xl p-5 sm:p-7"><h3 className="text-lg font-semibold">Send a message</h3><p className="mt-1 text-sm text-slate-400">A few details are enough to get started.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["name", "Name", "text"], ["email", "Email", "email"], ["subject", "Subject", "text"]].map(([name, label, type]) => <label key={name} className={name === "subject" ? "sm:col-span-2" : ""}><span className="mb-1.5 block text-xs font-medium text-slate-300">{label}</span><input required type={type} value={form[name as keyof typeof form]} onChange={(event) => setForm({ ...form, [name]: event.target.value })} className="w-full rounded-xl border border-white/10 bg-slate-950/50 px-3 py-3 text-sm outline-none transition placeholder:text-slate-600 focus:border-cyan-200/60"/></label>)}<label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-medium text-slate-300">Message</span><textarea required rows={4} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} className="w-full resize-none rounded-xl border border-white/10 bg-slate-950/50 px-3 py-3 text-sm outline-none transition focus:border-cyan-200/60"/></label></div>{status === "success" && <div role="status" className="form-success mt-4 flex items-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-3 py-2.5 text-sm text-emerald-200"><CheckCircle2 className="success-check size-5"/>Your message has been sent successfully.</div>}{status === "error" && <p role="alert" className="mt-4 text-sm text-rose-300">We couldn&apos;t send that message. Please email us directly.</p>}<button disabled={status === "sending"} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-cyan-300 px-5 text-sm font-semibold text-slate-950 transition hover:bg-cyan-200 disabled:opacity-70">{status === "sending" ? "Sending..." : "Send message"}<Send className="size-4"/></button></form></div></section>;
}
