import { ArrowUpRight, BriefcaseBusiness, Code2, Mail } from "lucide-react";

import Image from "next/image";

const nav = [["Services", "#services"], ["Process", "#process"], ["Our Work", "#work"], ["About", "#about"], ["Contact", "#contact"]];
const legal = [["Privacy Policy", "mailto:contact@proguardweb.com?subject=Privacy%20policy%20request"], ["Terms of Service", "mailto:contact@proguardweb.com?subject=Terms%20of%20service%20request"]];

export default function Footer() {
  return <footer data-reveal className="relative z-10 border-t border-white/10 px-6 py-8"><div className="container"><div className="flex flex-col justify-between gap-7 sm:flex-row"><div><a href="#home" className="flex items-center gap-2.5 font-bold tracking-tight"><Image src="/proguard-mark.svg" width={32} height={32} alt=""/>ProGuard <span className="text-cyan-300">Web</span></a><p className="mt-3 max-w-sm text-sm leading-6 text-slate-500">Web Design · Secure Hosting · SSL · Cybersecurity</p></div><div className="flex flex-wrap content-start gap-x-5 gap-y-3">{nav.map(([label, href]) => <a key={href} href={href} className="inline-flex items-center gap-1 text-sm text-slate-400 transition-colors duration-300 hover:text-cyan-200">{label}<ArrowUpRight className="size-3 transition-transform duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5"/></a>)}</div></div><div className="mt-7 flex flex-col gap-4 border-t border-white/10 pt-5 text-xs text-slate-600 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 ProGuard Web. All rights reserved.</p><div className="flex flex-wrap items-center gap-4">{legal.map(([label, href]) => <a key={label} href={href} aria-label={`Request ${label} by email`} className="transition-colors duration-300 hover:text-cyan-200">{label}</a>)}<a href="https://linkedin.com" aria-label="ProGuard Web on LinkedIn" className="transition-all duration-300 hover:-translate-y-0.5 hover:text-cyan-200"><BriefcaseBusiness className="size-4"/></a><a href="https://github.com" aria-label="ProGuard Web on GitHub" className="transition-all duration-300 hover:-translate-y-0.5 hover:text-cyan-200"><Code2 className="size-4"/></a><a href="mailto:contact@proguardweb.com" aria-label="Email ProGuard Web" className="transition-all duration-300 hover:-translate-y-0.5 hover:text-cyan-200"><Mail className="size-4"/></a></div></div></div></footer>;
}
